.PHONY: help clean demo example test

help:
	@echo "\
clean:   Flush all images generated by regression tests\n\
demo:    Start demo server\n\
help:    Show this help message\n\
example: Rebuild example pages\n\
test:    Run tests"

clean:
	@rm test/images/*/*.png

demo:
	@npm run start-demo-server

example:
	@npm run rebuild-examples

test:
	@npm run test
